language: dart

dart:
  - dev
  - 2.4.0

dart_task:
  - test: --platform vm,chrome,firefox
  - dartanalyzer: --fatal-infos --fatal-warnings .

matrix:
  include:
  - dart: dev
    dart_task: dartfmt

cache:
 directories:
   - $HOME/.pub-cache
